/**
 * @format
 */
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_ASYNC = 'REGISTER_USER_ASYNC'
export const LOGIN_GET_SUCCESS = 'LOGIN_GET_SUCCESS'
export const LOGIN_GET_ERROR = 'LOGIN_GET_ERROR'
export const LOGIN_GET_SUCCESS_ASYNC = 'LOGIN_GET_SUCCESS_ASYNC'
export const LOGOUT_GET_SUCCESS = 'LOGOUT_GET_SUCCESS'
export const LOGOUT_GET_SUCCESS_ASYNC = 'LOGOUT_GET_SUCCESS_ASYNC'


